#!/bin/sh

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>


case "$1" in
	configure)
		addgroup --system sshhoneypotd || true
		adduser --system --home /nonexistent --no-create-home --disabled-password --ingroup sshhoneypotd sshhoneypotd
		if [ -x "$(command -v ssh-keygen)" ]; then
			[ -f /etc/ssh-honeypotd/ssh_host_dsa_key ] || ssh-keygen -f /etc/ssh-honeypotd/ssh_host_dsa_key -N '' -t dsa  || true
			[ -f /etc/ssh-honeypotd/ssh_host_rsa_key ] || ssh-keygen -f /etc/ssh-honeypotd/ssh_host_rsa_key -N '' -t rsa  || true
			[ -f /etc/ssh-honeypotd/ssh_host_key ]     || ssh-keygen -f /etc/ssh-honeypotd/ssh_host_key     -N '' -t rsa1 || true
		else
			[ -f /etc/ssh-honeypotd/ssh_host_dsa_key ] || (cp -f /etc/ssh-honeypotd/ssh_host_dsa_key.dist /etc/ssh-honeypotd/ssh_host_dsa_key && cp -f /etc/ssh-honeypotd/ssh_host_dsa_key.pub.dist /etc/ssh-honeypotd/ssh_host_dsa_key.pub) || true
			[ -f /etc/ssh-honeypotd/ssh_host_rsa_key ] || (cp -f /etc/ssh-honeypotd/ssh_host_rsa_key.dist /etc/ssh-honeypotd/ssh_host_rsa_key && cp -f /etc/ssh-honeypotd/ssh_host_rsa_key.pub.dist /etc/ssh-honeypotd/ssh_host_rsa_key.pub) || true
			[ -f /etc/ssh-honeypotd/ssh_host_key ]     || (cp -f /etc/ssh-honeypotd/ssh_host_key.dist     /etc/ssh-honeypotd/ssh_host_key     && cp -f /etc/ssh-honeypotd/ssh_host_key.pub.dist     /etc/ssh-honeypotd/ssh_host_key.pub)     || true
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
